#!/bin/sh
set -e

PARENT=$(dirname $(dirname "$0"))
cd $PARENT/repos/

if [ -z "$1" ]; then
	echo 'hint: give source repository name'
	exit 1
fi
if [ -z "$2" ]; then
	echo 'hint: give new repository name'
	exit 1
fi

cp -r ./$1 ./$2
