#!/bin/sh
set -e

PARENT=$(pwd)
cd $PARENT/repos/

if [ "$1" = '--full' ]; then
	ls -lcAh
else
	print_if_bare_repo='
		if "$(git --git-dir="$1" rev-parse --is-bare-repository)" = true
		then
			printf "%s\n" "${1#./}"
		fi
	'
	find -type d -name "*.git" -exec sh -c "$print_if_bare_repo" -- \{} \; -prune 2>/dev/null
fi

