#!/bin/sh
set -e

cd "$(dirname "$0")"
cd ../repos/

if [ -z "$1" ]; then
	echo 'hint: give source repository name'
	exit 1
fi
if [ -z "$2" ]; then
	echo 'hint: give new repository name'
	exit 1
fi

mv ./$1 ./$2
